version: '3.7'
services:
  nginx:
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-stream: nginx
        awslogs-group: pyli
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
    image: nginx:1.17
    volumes:
      - ./pyli_api/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - backend

  redis:
    image: redis
    ports:
      - 6379:6379


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5051:80

  worker:
    container_name: worker
    logging:
      driver: awslogs
      options:
      awslogs-region: us-east-2
      awslogs-stream: backend
      awslogs-group: pyli
      tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
  build:
    context: pyli_api
    dockerfile: Dockerfile
  command: python app/main.py
  tty: true
  volumes:
    - ./pyli_api:/app/:cached
    - ./.docker/.ipython:/root/.ipython:cached
  environment:
    PYTHONPATH: .
    DATABASE_URL: 'postgresql://postgres:aMbROISeStiVIN@database-1.cxnpwdvrh2yh.us-east-2.rds.amazonaws.com:5432/postgres'
    SECRET_KEY: 'kwgsoftworks'
    ALGORITHM: 'HS256'
    ACCESS_TOKEN_EXPIRE_MINUTES: 30
    API_V1_STR: '/api/v1'
    LOCAL_PORT: 80
    LOCAL_HOST: '0.0.0.0'

volumes:
  db-data:

