targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/src/helpers/api_gen/src/'
          output_folder: 'lib/src/helpers/api_gen/generated/'
         